# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - python: '3.9'
            toxenv: py39
            os: ubuntu-latest
          - python: '3.10'
            toxenv: py310
            os: ubuntu-latest
          - python: '3.11'
            toxenv: py311
            os: ubuntu-latest
          - python: '3.7'
            toxenv: py37
            os: macos-latest
          - python: '3.8'
            toxenv: py38
            os: macos-latest
          - python: '3.9'
            toxenv: py39
            os: macos-latest
          - python: '3.10'
            toxenv: py310
            os: windows-latest
          - python: '3.11'
            toxenv: py311
            os: windows-latest
          - python: '3.7'
            toxenv: py37
            os: windows-latest
          - python: '3.8'
            toxenv: py38
            os: windows-latest
          - python: '3.9'
            toxenv: py39
            os: windows-latest
          - python: '3.10'
            toxenv: py310
            os: windows-latest
          - python: '3.11'
            toxenv: py311
            os: windows-latest
          - python: '3.12'
            toxenv: py312
            os: windows-latest
          - python: '3.13'
            toxenv: py313
            os: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox
        env:
          FORCE_COLOR: yes
          TOXENV: ${{ matrix.toxenv }}
